project_id = "jkywmvvgpvmqheeevzvn"

[functions.ai-chat]
verify_jwt = true

[functions.voice-transcribe]
verify_jwt = true

[functions.transaction-chat]
verify_jwt = true

[functions.education-chat]
verify_jwt = true

[functions.home-chat]
verify_jwt = true
