project_id = "jkywmvvgpvmqheeevzvn"

[functions.ai-chat]
verify_jwt = false

[functions.voice-transcribe]
verify_jwt = false

[functions.transaction-chat]
verify_jwt = false

[functions.education-chat]
verify_jwt = false
